// import React from 'react';
// import Button from 'react-bootstrap/Button';

// // import { joinMission } from '../redux/missions/MissionsStore';

// function MissionBookingUI() {
//     return (
//         <>
//           {!reserved && (
//             <Button variant="outline-dark">Join Mission</Button>
//         )}
//           {reserved && (
//             <Button variant="outline-dark">Leave Mission</Button>
//         )}
        
//         </>
//     )
// }

// export default MissionBookingUI
